<?php
/**
 * AdminApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WKDClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WKD Admin API
 *
 * API to manage OpenPGP public keys in a Web Key Directory
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace WKDClient;

use WKDClient\Configuration;
use WKDClient\ApiException;
use WKDClient\ObjectSerializer;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  WKDClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdminApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAdminKeyClass
     *
     * .
     *
     */
    public function testDeleteAdminKeyClass()
    {
    }

    /**
     * Test case for getAdminKeyClass
     *
     * .
     *
     */
    public function testGetAdminKeyClass()
    {
    }

    /**
     * Test case for postAdminKeyClass
     *
     * .
     *
     */
    public function testPostAdminKeyClass()
    {
    }
}
